acl safe_ports port 80 443
acl monitor_network src 10.77.0.0/24

acl metadata_hosts dstdomain \
    localhost \
    localhost.localdomain \
    metadata \
    metadata.google.internal
acl metadata_ipv4 dst 169.254.169.254/32
acl forbidden_ipv4 dst \
    0.0.0.0/8 \
    10.0.0.0/8 \
    100.64.0.0/10 \
    127.0.0.0/8 \
    169.254.0.0/16 \
    172.16.0.0/12 \
    192.0.0.0/24 \
    192.0.2.0/24 \
    192.88.99.0/24 \
    192.168.0.0/16 \
    198.18.0.0/15 \
    198.51.100.0/24 \
    203.0.113.0/24 \
    224.0.0.0/4 \
    240.0.0.0/4
acl forbidden_ipv6 dst \
    ::/128 \
    ::1/128 \
    ::ffff:0:0/96 \
    64:ff9b::/96 \
    64:ff9b:1::/48 \
    100::/64 \
    2001::/23 \
    2001:db8::/32 \
    2002::/16 \
    3fff::/20 \
    5f00::/16 \
    fc00::/7 \
    fe80::/10 \
    ff00::/8

http_access deny !safe_ports
http_access deny metadata_hosts
http_access deny metadata_ipv4
http_access deny forbidden_ipv4
http_access deny forbidden_ipv6
http_access allow monitor_network safe_ports
http_access deny all

request_header_access Accept-Encoding deny all
request_header_add Accept-Encoding identity
reply_body_max_size 10485760 allow all

cache deny all
cache_dir null /tmp
access_log none
cache_log /dev/null
cache_store_log none
logfile_rotate 0
pid_filename /tmp/squid.pid
http_port 3128
